name: variables and sectrets
env:
  WF_VAR: "Workflow level variable"

on:
  push:
    branches:
      - main

jobs:
  test_variables:
    env:
      JOB_VAR: "This is job level variable"
    name: job to test variables
    runs-on: ubuntu-latest
    steps:
      - name: test variables
        id: stepVar
        env:
          STEP_VAR: "This is step level variable"
        run: |
          echo ${{ github.actor }}
          echo $GITHUB_JOB
          echo $WF_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo ${{ vars.CONF_VAR }}
          echo ${{ secrets.A_SECRET }}
